//
// Created by matthias on 04.11.20.
//

#ifndef PAPERLESS_CIRCULARNONBLOCKINGQUEUE_H
#define PAPERLESS_CIRCULARNONBLOCKINGQUEUE_H


class CircularNonBlockingQueue {

};


#endif //PAPERLESS_CIRCULARNONBLOCKINGQUEUE_H
